id = "cypher-neo4j-44"
name = "Cypher (Neo4j 4.4)"
version = "0.0.1"
schema_version = 1
authors = ["TTorr3s <is.jesustorres@icloud.com>"]
description = "Syntax highlighting for the Cypher query language, tuned for Neo4j 4.4 Community Edition."
repository = "https://github.com/TTorr3s/cypher-neo4j"

[grammars.cypher]
repository = "https://github.com/TTorr3s/tree-sitter-cypher-neo4j"
commit = "17d10c19d143efbe8f42ba834d72f91a6286ab4c"
